# Generated by Django 3.2.11 on 2022-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyCode', models.IntegerField(null=True)),
                ('companyName', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=10)),
                ('closingMonth', models.DateTimeField(null=True)),
                ('revenue', models.IntegerField(null=True)),
            ],
        ),
    ]
