# Generated by Django 3.2.11 on 2022-02-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_excelfileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFileUpload',
        ),
    ]
