# Generated by Django 3.2.11 on 2022-02-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_excelfileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='files',
            new_name='file',
        ),
    ]
