# Generated by Django 3.2.11 on 2022-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_files_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='classification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='companyCode',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='filedata',
            name='companyName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
