# Generated by Django 3.2.11 on 2022-02-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220211_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedata',
            name='closingMonth',
            field=models.DateField(null=True),
        ),
    ]
