# Generated by Django 3.2.11 on 2022-02-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_filedata_closingmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedata',
            name='netIncome',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filedata',
            name='operatingIncome',
            field=models.IntegerField(null=True),
        ),
    ]
