# Generated by Django 3.2.11 on 2022-02-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220211_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, default='filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploader',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
