# Generated by Django 4.0.4 on 2022-05-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_file_id_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
