# Generated by Django 4.0.4 on 2022-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='companyCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
